"""
Local Execution Baseline  (Table I — Row 6)
=============================================
All tasks executed locally at the WD (IoT device).  No UAV offloading.

Policy (rule-based, no learning):
  Every task generated by an IoT device is computed locally using the
  device's own CPU.  The UAV fleet is deployed but receives no task
  offloads from any WD.  This simulates the scenario where no MEC
  infrastructure assistance is available.

  Actions emitted: all dimensions set to -1.0 (after tanh → minimum),
  which the environment interprets as "execute locally".

This serves as the absolute lower bound (baseline floor) for all
MEC-based methods — any learned or heuristic offloading policy should
outperform local execution in terms of latency and energy under the
default task model.

Interface (identical to MAPPOAgent):
    get_actions(obs_all, state, num_active) → actions(-1), log_probs(=0), values(=0)
    get_values(state)                       → zeros
    update(buffer)                          → empty metrics (no learning)
    save(path) / load(path)                 → no-ops
"""

import os
import sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))


class LocalExecutionAgent:
    """
    Local Execution baseline (Row 6).

    Rule-based: always emits -1.0 for every action dimension so the
    environment computes every task locally at the IoT device.
    No neural network, no training.
    """

    METHOD = "LocalExecution"

    def __init__(self, obs_dim, state_dim, action_dim, n_agents,
                 device="cpu", share_actor=False):
        self.obs_dim    = obs_dim
        self.state_dim  = state_dim
        self.action_dim = action_dim
        self.n_agents   = n_agents
        self.device     = device
        self.total_updates = 0

        # tanh(-∞) → -1  →  env interprets as "do not offload"
        self._local_action = np.full(action_dim, -1.0, dtype=np.float32)

        # Signal for env detection (optional)
        self.LOCAL_ONLY_MODE = True

    # ----------------------------------------------------------
    # Action selection
    # ----------------------------------------------------------
    def get_actions(self, obs_all, state, num_active=None):
        """
        Return all-(-1) actions for every active agent.
        Environment maps these to local compute for every IoT device.
        """
        n_active  = num_active or self.n_agents
        actions   = np.zeros((self.n_agents, self.action_dim), dtype=np.float32)
        log_probs = np.zeros(self.n_agents, dtype=np.float32)
        values    = np.zeros(self.n_agents, dtype=np.float32)
        for i in range(n_active):
            actions[i] = self._local_action
        return actions, log_probs, values

    def get_values(self, state):
        return np.zeros(self.n_agents, dtype=np.float32)

    # ----------------------------------------------------------
    # No learning
    # ----------------------------------------------------------
    def update(self, buffer=None) -> dict:
        """Rule-based agent: no gradient updates."""
        return dict(actor_loss=0.0, critic_loss=0.0,
                    entropy=0.0, approx_kl=0.0)

    # ----------------------------------------------------------
    # Checkpoint
    # ----------------------------------------------------------
    def save(self, path: str):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        import json
        meta = {'method': self.METHOD, 'total_updates': self.total_updates}
        with open(path.replace('.pt', '.json'), 'w') as f:
            json.dump(meta, f, indent=2)

    def load(self, path: str):
        pass
